-- Generated by Oracle SQL Developer Data Modeler 18.3.0.268.1208
--   at:        2019-01-04 22:54:07 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g


set echo on
CREATE OR REPLACE PROCEDURE "ZRUS_ALL_OBJEKTY_SCHEMATU" AS
-- pokud v logu bude uvedeno, ze nektery objekt nebyl zrusen, protoze na nej jiny jeste existujici objekt stavi,
-- spust proceduru opakovane, dokud se nezrusi vse
v_pom PLS_INTEGER;
BEGIN
LOOP
FOR irec IN (SELECT DISTINCT
                    object_type,object_name,
                    'drop '||object_type||' "'||object_name||'"'||
                    CASE object_type WHEN 'TABLE' THEN ' cascade constraints purge'
                                     ELSE ' '
                    END AS prikaz
              FROM user_objects
              WHERE object_name <> 'ZRUS_ALL_OBJEKTY_SCHEMATU'
            )
  LOOP
   BEGIN
   DBMS_OUTPUT.put_line('prikaz '||irec.prikaz);
      EXECUTE IMMEDIATE irec.prikaz;
   EXCEPTION
      WHEN OTHERS THEN DBMS_OUTPUT.put('nen� ');
   END;
   DBMS_OUTPUT.put_line('zrusen(a) '||irec.object_type||' '||irec.object_name);
  END LOOP;
SELECT COUNT(*) INTO v_pom
FROM user_objects
WHERE object_name <> 'ZRUS_ALL_OBJEKTY_SCHEMATU';
EXIT WHEN v_pom = 0;
END LOOP;
DBMS_OUTPUT.put_line('hotovo!');
END ZRUS_ALL_OBJEKTY_SCHEMATU;
/
execute ZRUS_ALL_OBJEKTY_SCHEMATU


CREATE TABLE dodanie (
    id_vydaj      INTEGER NOT NULL,
    id_obj        INTEGER NOT NULL,
    spz           VARCHAR2(8 CHAR) NOT NULL,
    vzdialenost   INTEGER NOT NULL
);

COMMENT ON TABLE dodanie IS
    'Zaznam o dodani materialu objednavky.';

COMMENT ON COLUMN dodanie.vzdialenost IS
    'Vzdialenost medzi lomom, dodaciou adresou a spat. Sofer nesmie prejst viac ako 400 kilometrov za den.';

CREATE UNIQUE INDEX ix_dodanie_ ON
    dodanie (
        id_vydaj
    ASC );

ALTER TABLE dodanie
    ADD CONSTRAINT pk_dodanie PRIMARY KEY ( id_vydaj,
                                            spz,
                                            id_obj );

CREATE TABLE lom (
    meno_lom   VARCHAR2(20 CHAR) NOT NULL,
    rozloha    INTEGER
);

COMMENT ON TABLE lom IS
    'Evidencia lomov.';

COMMENT ON COLUMN lom.meno_lom IS
    'Meno lomu.';

COMMENT ON COLUMN lom.rozloha IS
    'Na akom uzemi sa lom rozprestiera.';

ALTER TABLE lom ADD CONSTRAINT pk_lom PRIMARY KEY ( meno_lom );

CREATE TABLE material (
    datum            DATE NOT NULL,
    material         VARCHAR2(20 CHAR) NOT NULL,
    hmotnost_sklad   INTEGER NOT NULL,
    zisk             INTEGER NOT NULL,
    vydaj            INTEGER NOT NULL
);

COMMENT ON TABLE material IS
    'Zaznam o vahe materialu na konci pracovneho dna.';

COMMENT ON COLUMN material.datum IS
    'Den v ktory bol vytvoreni zaznam.';

COMMENT ON COLUMN material.material IS
    'Druh materialu.
Piesok
Strk: drt (0-4), drt (4-8),
Uhlie: hrasok (8-20), orech (20-50)';

COMMENT ON COLUMN material.hmotnost_sklad IS
    'Vaha materialu na konci daneho dna.';

COMMENT ON COLUMN material.zisk IS
    'Kolko materialu sme ziskali za dany den. ';

COMMENT ON COLUMN material.vydaj IS
    'Kolko materialu sme vydali za dany den.';

ALTER TABLE material ADD CONSTRAINT pk_material PRIMARY KEY ( material,
                                                              datum );

CREATE TABLE objednavka (
    id_obj         INTEGER NOT NULL,
    id_odb         INTEGER NOT NULL,
    material_obj   VARCHAR2(20) NOT NULL,
    hmotnost_obj   INTEGER NOT NULL,
    datum_obj      DATE,
    adresa_obj     VARCHAR2(50 CHAR)
);

COMMENT ON TABLE objednavka IS
    'Evidencia objednavok.';

COMMENT ON COLUMN objednavka.id_obj IS
    'Cislo objednavky.';

COMMENT ON COLUMN objednavka.material_obj IS
    'Druh objednaneho materialu.';

COMMENT ON COLUMN objednavka.hmotnost_obj IS
    'Vaha objednaneho materialu.';

COMMENT ON COLUMN objednavka.datum_obj IS
    'Datum vydaja objednavky, nevyplnuje sa ak je objednavka vydana v den objednania.';

COMMENT ON COLUMN objednavka.adresa_obj IS
    'Adresa na ktoru ma byt dodani material, nevyplnuje sa ak si odberatel zabezpeci vlastnu dopravu.';

ALTER TABLE objednavka ADD CONSTRAINT pk_objednavka PRIMARY KEY ( id_obj );

CREATE TABLE odberatel (
    id_odb        INTEGER NOT NULL,
    meno_odb      VARCHAR2(50 CHAR) NOT NULL,
    adresa_odb    VARCHAR2(50 CHAR) NOT NULL,
    kontakt_odb   VARCHAR2(50 CHAR) NOT NULL
);

COMMENT ON TABLE odberatel IS
    'Zoznam odberatelov.';

COMMENT ON COLUMN odberatel.id_odb IS
    'Cislo odberatela.';

COMMENT ON COLUMN odberatel.meno_odb IS
    'Meno a  priezvisko  odeberatela.';

COMMENT ON COLUMN odberatel.adresa_odb IS
    'Trvale bydlisto  odberatela.';

COMMENT ON COLUMN odberatel.kontakt_odb IS
    'Kontakt na odberatela.';

ALTER TABLE odberatel ADD CONSTRAINT pk_odberatel PRIMARY KEY ( id_odb );

CREATE TABLE praca (
    id_praca          INTEGER NOT NULL,
    datum             DATE NOT NULL,
    meno_lom          VARCHAR2(20 CHAR) NOT NULL,
    material          VARCHAR2(20 CHAR) NOT NULL,
    hmotnost_praca    INTEGER NOT NULL,
    cas_tazba         INTEGER,
    typ_spracovanie   VARCHAR2(20 CHAR),
    id_vydaj          INTEGER,
    cas_spracovanie   INTEGER
);

COMMENT ON TABLE praca IS
    'Evidencia prac konanych v lome.';

COMMENT ON COLUMN praca.id_praca IS
    'Cislo prace.';

COMMENT ON COLUMN praca.datum IS
    'Den vykonu prace.';

COMMENT ON COLUMN praca.material IS
    'Druh materialu ziskaneho pracov v lome.';

COMMENT ON COLUMN praca.hmotnost_praca IS
    'Konecna vaha ziskaneho materialu.';

COMMENT ON COLUMN praca.cas_tazba IS
    'Zaznam o skrateni alebo predlzeni tazby.';

COMMENT ON COLUMN praca.typ_spracovanie IS
    'Popis o aky druh spracovania sa jedna.';

COMMENT ON COLUMN praca.cas_spracovanie IS
    'Zaznam o skrateni alebo predlzeni spracovania.';

ALTER TABLE praca ADD CONSTRAINT pk_praca PRIMARY KEY ( id_praca );

CREATE TABLE pracovnik (
    id_zam    INTEGER NOT NULL,
    pozicia   VARCHAR2(30 CHAR) NOT NULL
);

COMMENT ON TABLE pracovnik IS
    'Evidencia pracovnikov lomu';

COMMENT ON COLUMN pracovnik.pozicia IS
    'Aku funkciu plni zamestnanec.';

ALTER TABLE pracovnik ADD CONSTRAINT pk_pracovnik PRIMARY KEY ( id_zam );

CREATE TABLE sichta (
    id_praca       INTEGER NOT NULL,
    id_zam         INTEGER NOT NULL,
    id_vybavenie   INTEGER,
    cas_sichta     INTEGER
);

COMMENT ON TABLE sichta IS
    'Zaznam o vykonanej praci zamestnancami v lome.';

COMMENT ON COLUMN sichta.cas_sichta IS
    'Zaznamenavame iba ak  je praovna doba ina ako 8 hodin.';

ALTER TABLE sichta ADD CONSTRAINT pk_sichta PRIMARY KEY ( id_zam,
                                                          id_praca );

CREATE TABLE sofer (
    id_zam                       INTEGER NOT NULL,
    skupina_vodickeho_preukazu   VARCHAR2(3 CHAR) NOT NULL
);

COMMENT ON TABLE sofer IS
    'Evidencia zamestnanych soferov.
';

COMMENT ON COLUMN sofer.id_zam IS
    '
';

COMMENT ON COLUMN sofer.skupina_vodickeho_preukazu IS
    'Sofer patri do skupiny vodicskeho opravnenia
C     - do 3 500 kg
C1   - od 3500 kg do 7 500 kg
C1E - do 12 000 kg';

ALTER TABLE sofer ADD CONSTRAINT pk_sofer PRIMARY KEY ( id_zam );

CREATE TABLE vozidlo (
    spz       VARCHAR2(8 CHAR) NOT NULL,
    id_zam    INTEGER,
    nosnost   INTEGER NOT NULL
);

COMMENT ON TABLE vozidlo IS
    'Evidencia vozidiel urcenych na dopravu materialu.';

COMMENT ON COLUMN vozidlo.spz IS
    'Statna poznavacia znacka vozidla. Ak vozidlo nema priradeneho sofera, nepouziva sa dodanie.';

COMMENT ON COLUMN vozidlo.nosnost IS
    'Maximalny naklad vozidla.';

ALTER TABLE vozidlo ADD CONSTRAINT pk_vozidlo PRIMARY KEY ( spz );

CREATE TABLE vybavenie (
    id_vybavenie    INTEGER NOT NULL,
    meno_lom        VARCHAR2(20 CHAR) NOT NULL,
    typ_vybavenie   VARCHAR2(30 CHAR) NOT NULL
);

COMMENT ON TABLE vybavenie IS
    'Zaznam vybavenia a strojov lomov.';

COMMENT ON COLUMN vybavenie.id_vybavenie IS
    'Cislo vybavenia.';

COMMENT ON COLUMN vybavenie.typ_vybavenie IS
    'Popis o ake vybavenie sa jedna.';

ALTER TABLE vybavenie ADD CONSTRAINT pk_vybavenie PRIMARY KEY ( id_vybavenie );

CREATE TABLE vydaj (
    id_vydaj            INTEGER NOT NULL,
    id_obj              INTEGER,
    datum               DATE NOT NULL,
    material            VARCHAR2(20 CHAR) NOT NULL,
    hmotnost_vydaj      INTEGER NOT NULL,
    novy_zostatok_obj   INTEGER NOT NULL
);

COMMENT ON TABLE vydaj IS
    'Evidencia vydaju materialu z lomov.';

COMMENT ON COLUMN vydaj.id_vydaj IS
    'Cislo vydaja materialu na objednavku.';

COMMENT ON COLUMN vydaj.datum IS
    'Datum vydaja materialu.';

COMMENT ON COLUMN vydaj.material IS
    'Druh vydaneho materialu.';

COMMENT ON COLUMN vydaj.hmotnost_vydaj IS
    'Vaha vydaneho materialu.';

COMMENT ON COLUMN vydaj.novy_zostatok_obj IS
    'Kolko materialu este chyba do dokncenia objednavky.';

ALTER TABLE vydaj ADD CONSTRAINT pk_vydaj PRIMARY KEY ( id_vydaj );

CREATE TABLE zamestnanec (
    id_zam        INTEGER NOT NULL,
    meno_zam      VARCHAR2(50 CHAR) NOT NULL,
    adresa_zam    VARCHAR2(50 CHAR) NOT NULL,
    kontakt_zam   VARCHAR2(50 CHAR) NOT NULL
);

COMMENT ON TABLE zamestnanec IS
    'Evidencia zamestnancov  lomov.';

COMMENT ON COLUMN zamestnanec.id_zam IS
    'Cislo zamestnanca.';

COMMENT ON COLUMN zamestnanec.meno_zam IS
    'Meno a priezvisko zamestnanca.';

COMMENT ON COLUMN zamestnanec.adresa_zam IS
    'Trvale bydlisto zamestnanca.';

COMMENT ON COLUMN zamestnanec.kontakt_zam IS
    'Kontak na zamestnanca.';

ALTER TABLE zamestnanec ADD CONSTRAINT pk_zamestnanec PRIMARY KEY ( id_zam );

ALTER TABLE dodanie
    ADD CONSTRAINT fk_dodanie_objednavka FOREIGN KEY ( id_obj )
        REFERENCES objednavka ( id_obj );

ALTER TABLE dodanie
    ADD CONSTRAINT fk_dodanie_vozidlo FOREIGN KEY ( spz )
        REFERENCES vozidlo ( spz );

ALTER TABLE dodanie
    ADD CONSTRAINT fk_dodanie_vydaj FOREIGN KEY ( id_vydaj )
        REFERENCES vydaj ( id_vydaj );

ALTER TABLE objednavka
    ADD CONSTRAINT fk_objednavka_odberatel FOREIGN KEY ( id_odb )
        REFERENCES odberatel ( id_odb );

ALTER TABLE praca
    ADD CONSTRAINT fk_praca_lom FOREIGN KEY ( meno_lom )
        REFERENCES lom ( meno_lom );

ALTER TABLE praca
    ADD CONSTRAINT fk_praca_material FOREIGN KEY ( material,
                                                   datum )
        REFERENCES material ( material,
                              datum );

ALTER TABLE praca
    ADD CONSTRAINT fk_praca_vydaj FOREIGN KEY ( id_vydaj )
        REFERENCES vydaj ( id_vydaj );

ALTER TABLE pracovnik
    ADD CONSTRAINT fk_pracovnik_zamestnanec FOREIGN KEY ( id_zam )
        REFERENCES zamestnanec ( id_zam );

ALTER TABLE sichta
    ADD CONSTRAINT fk_sichta_praca FOREIGN KEY ( id_praca )
        REFERENCES praca ( id_praca );

ALTER TABLE sichta
    ADD CONSTRAINT fk_sichta_pracovnik FOREIGN KEY ( id_zam )
        REFERENCES pracovnik ( id_zam );

ALTER TABLE sichta
    ADD CONSTRAINT fk_sichta_vybavenie FOREIGN KEY ( id_vybavenie )
        REFERENCES vybavenie ( id_vybavenie );

ALTER TABLE sofer
    ADD CONSTRAINT fk_sofer_zamestnanec FOREIGN KEY ( id_zam )
        REFERENCES zamestnanec ( id_zam );

ALTER TABLE vozidlo
    ADD CONSTRAINT fk_vozidlo_sofer FOREIGN KEY ( id_zam )
        REFERENCES sofer ( id_zam );

ALTER TABLE vybavenie
    ADD CONSTRAINT fk_vybavenie_lom FOREIGN KEY ( meno_lom )
        REFERENCES lom ( meno_lom );

ALTER TABLE vydaj
    ADD CONSTRAINT fk_vydaj_material FOREIGN KEY ( material,
                                                   datum )
        REFERENCES material ( material,
                              datum );

ALTER TABLE vydaj
    ADD CONSTRAINT fk_vydaj_objednavka FOREIGN KEY ( id_obj )
        REFERENCES objednavka ( id_obj );


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             1
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
